import os
import json
import subprocess
import sys

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler


INCIDENT_FILE = "data/incidents.json"
REPORT_FILE = "output/incident_report.json"


app = App(
    token=os.environ["SLACK_BOT_TOKEN"]
)


def load_incidents():
    with open(INCIDENT_FILE, "r", encoding="utf-8") as file:
        return json.load(file)


def save_incidents(incidents):
    with open(INCIDENT_FILE, "w", encoding="utf-8") as file:
        json.dump(incidents, file, indent=2)


def load_report():
    with open(REPORT_FILE, "r", encoding="utf-8") as file:
        return json.load(file)


def build_slack_summary(report):
    metrics = report["dashboard_metrics"]

    message = (
        "*AI Incident Intelligence Summary*\n\n"
        f"*Total Issues:* {metrics['total_issues']}\n"
        f"*Open Issues:* {metrics['open_issues']}\n"
        f"*Resolved Issues:* {metrics['resolved_issues']}\n"
        f"*High Severity:* {metrics['high_severity_issues']}\n"
        f"*Recurring Issue Types:* {metrics['recurring_issue_types']}\n"
        f"*Security Flags:* {metrics['security_flags']}\n"
        f"*Compliance Flags:* {metrics['compliance_flags']}\n"
        f"*Average Resolution Time:* "
        f"{metrics['average_resolution_time_minutes']} minutes\n\n"
    )

    message += "*Recurring Issues:*\n"

    if report["recurring_issues"]:
        for issue, count in report["recurring_issues"].items():
            message += f"• {issue} — {count} occurrences\n"
    else:
        message += "• None identified\n"

    message += "\n*Security Concerns:*\n"

    if report["security_concerns"]:
        for incident_id in report["security_concerns"]:
            message += f"• {incident_id} — requires investigation\n"
    else:
        message += "• None identified\n"

    message += "\n*Compliance Concerns:*\n"

    if report["compliance_concerns"]:
        for incident_id in report["compliance_concerns"]:
            message += f"• {incident_id} — requires human review\n"
    else:
        message += "• None identified\n"

    message += "\n*Preventive Actions:*\n"

    for action in report["preventive_actions"]:
        message += f"• {action}\n"

    return message


def run_incident_analysis():
    """
    Run the existing incident analysis script.
    """

    result = subprocess.run(
        [sys.executable, "incident_analysis.py"],
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"Incident analysis failed:\n{result.stderr}"
        )


def generate_dashboard():
    """
    Regenerate the HTML dashboard using the
    latest incident report.
    """

    result = subprocess.run(
        [sys.executable, "dashboard_generator.py"],
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"Dashboard generation failed:\n{result.stderr}"
        )


def parse_incident_message(text):
    """
    Expected Slack format:

    INCIDENT-008 | High | Security | Open | Suspicious login activity
    """

    parts = [part.strip() for part in text.split("|")]

    if len(parts) != 5:
        return None

    incident_id = parts[0]
    severity = parts[1]
    category = parts[2]
    status = parts[3]
    issue = parts[4]

    if not incident_id.startswith("INCIDENT-"):
        return None

    valid_severities = {
        "Low",
        "Medium",
        "High",
        "Critical"
    }

    valid_statuses = {
        "Open",
        "Resolved"
    }

    if severity not in valid_severities:
        return None

    if status not in valid_statuses:
        return None

    if not category or not issue:
        return None

    return {
        "incident_id": incident_id,
        "severity": severity,
        "category": category,
        "issue": issue,
        "status": status,
        "description": issue,
        "resolution_time_minutes": 0
    }


@app.event("message")
def handle_message(event, say):
    """
    Listen for normal Slack channel messages.

    If the message matches the incident format:
    1. Save the incident.
    2. Run incident analysis.
    3. Regenerate the dashboard.
    """

    # Ignore messages generated by bots/apps.
    if event.get("bot_id"):
        return

    # Ignore message subtypes.
    if event.get("subtype"):
        return

    text = event.get("text", "").strip()

    incident = parse_incident_message(text)

    # Ignore normal Slack messages.
    if incident is None:
        return

    incidents = load_incidents()

    # Prevent duplicate incident IDs.
    existing_ids = {
        item["incident_id"]
        for item in incidents
    }

    if incident["incident_id"] in existing_ids:
        say(
            f"⚠️ {incident['incident_id']} already exists. "
            "No duplicate incident was added."
        )
        return

    # Add the incident.
    incidents.append(incident)

    save_incidents(incidents)

    try:
        # Update the analysis report.
        run_incident_analysis()

        # Update the dashboard.
        generate_dashboard()

        say(
            f"✅ *{incident['incident_id']} captured successfully.*\n\n"
            f"*Severity:* {incident['severity']}\n"
            f"*Category:* {incident['category']}\n"
            f"*Status:* {incident['status']}\n"
            f"*Issue:* {incident['issue']}\n\n"
            "Incident analysis and dashboard have been updated."
        )

    except Exception as error:
        say(
            f"⚠️ {incident['incident_id']} was saved, "
            f"but the analysis/dashboard update failed:\n{error}"
        )


@app.command("/analyze-incidents")
def analyze_incidents_command(ack, respond):
    ack()

    try:
        report = load_report()
        summary = build_slack_summary(report)

        respond(
            response_type="in_channel",
            text=summary
        )

    except Exception as error:
        respond(
            response_type="in_channel",
            text=f"Incident analysis could not be completed: {error}"
        )


if __name__ == "__main__":
    handler = SocketModeHandler(
        app,
        os.environ["SLACK_APP_TOKEN"]
    )

    print("AI Incident Intelligence Slack App is running...")

    handler.start()